//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.13 at 07:42:23 PM CEST 
//


package src.classes;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the classes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Root_QNAME = new QName("", "root");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: classes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RootType }
     * 
     */
    public RootType createRootType() {
        return new RootType();
    }

    /**
     * Create an instance of {@link ListaGatunk�wType }
     * 
     */
    public ListaGatunk�wType createListaGatunk�wType() {
        return new ListaGatunk�wType();
    }

    /**
     * Create an instance of {@link PiosenkaReferenceType }
     * 
     */
    public PiosenkaReferenceType createPiosenkaReferenceType() {
        return new PiosenkaReferenceType();
    }

    /**
     * Create an instance of {@link ListaWykonawc�wType }
     * 
     */
    public ListaWykonawc�wType createListaWykonawc�wType() {
        return new ListaWykonawc�wType();
    }

    /**
     * Create an instance of {@link WykonawcaType }
     * 
     */
    public WykonawcaType createWykonawcaType() {
        return new WykonawcaType();
    }

    /**
     * Create an instance of {@link ArtystaType }
     * 
     */
    public ArtystaType createArtystaType() {
        return new ArtystaType();
    }

    /**
     * Create an instance of {@link MetadaneType }
     * 
     */
    public MetadaneType createMetadaneType() {
        return new MetadaneType();
    }

    /**
     * Create an instance of {@link PiosenkaType }
     * 
     */
    public PiosenkaType createPiosenkaType() {
        return new PiosenkaType();
    }

    /**
     * Create an instance of {@link GatunekType }
     * 
     */
    public GatunekType createGatunekType() {
        return new GatunekType();
    }

    /**
     * Create an instance of {@link PlajlistaType }
     * 
     */
    public PlajlistaType createPlajlistaType() {
        return new PlajlistaType();
    }

    /**
     * Create an instance of {@link AutorType }
     * 
     */
    public AutorType createAutorType() {
        return new AutorType();
    }

    /**
     * Create an instance of {@link ListaPiosenekType }
     * 
     */
    public ListaPiosenekType createListaPiosenekType() {
        return new ListaPiosenekType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RootType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "root")
    public JAXBElement<RootType> createRoot(RootType value) {
        return new JAXBElement<RootType>(_Root_QNAME, RootType.class, null, value);
    }

}
