//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.13 at 08:28:54 PM CEST 
//


package src.classes;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for piosenkaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="piosenkaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="czas_trwania" type="{}czas"/>
 *         &lt;element name="album" type="{}stringtype"/>
 *         &lt;element name="rok_wydania" type="{}inttype"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}piosenkaAtrrGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "piosenkaType", propOrder = {
    "czasTrwania",
    "album",
    "rokWydania"
})
public class PiosenkaType {

    @XmlElement(name = "czas_trwania", required = true)
    protected String czasTrwania;
    @XmlElement(required = true)
    protected String album;
    @XmlElement(name = "rok_wydania", required = true)
    protected BigInteger rokWydania;
    @XmlAttribute(name = "tytul")
    protected String tytul;
    @XmlAttribute(name = "nastroj")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nastroj;
    @XmlAttribute(name = "gatunek", required = true)
    protected String gatunek;
    @XmlAttribute(name = "wykonawca", required = true)
    protected String wykonawca;

    /**
     * Gets the value of the czasTrwania property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCzasTrwania() {
        return czasTrwania;
    }

    /**
     * Sets the value of the czasTrwania property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCzasTrwania(String value) {
        this.czasTrwania = value;
    }

    /**
     * Gets the value of the album property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlbum() {
        return album;
    }

    /**
     * Sets the value of the album property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlbum(String value) {
        this.album = value;
    }

    /**
     * Gets the value of the rokWydania property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRokWydania() {
        return rokWydania;
    }

    /**
     * Sets the value of the rokWydania property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRokWydania(BigInteger value) {
        this.rokWydania = value;
    }

    /**
     * Gets the value of the tytul property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTytul() {
        return tytul;
    }

    /**
     * Sets the value of the tytul property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTytul(String value) {
        this.tytul = value;
    }

    /**
     * Gets the value of the nastroj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNastroj() {
        if (nastroj == null) {
            return "niezidentyfikowana";
        } else {
            return nastroj;
        }
    }

    /**
     * Sets the value of the nastroj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNastroj(String value) {
        this.nastroj = value;
    }

    /**
     * Gets the value of the gatunek property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGatunek() {
        return gatunek;
    }

    /**
     * Sets the value of the gatunek property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGatunek(String value) {
        this.gatunek = value;
    }

    /**
     * Gets the value of the wykonawca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWykonawca() {
        return wykonawca;
    }

    /**
     * Sets the value of the wykonawca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWykonawca(String value) {
        this.wykonawca = value;
    }

}
