//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.13 at 08:28:54 PM CEST 
//


package src.classes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for rootType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rootType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="metadane" type="{}metadaneType"/>
 *         &lt;element name="lista_gatunkow" type="{}lista_gatunkowType"/>
 *         &lt;element name="lista_wykonawcow" type="{}lista_wykonawcowType"/>
 *         &lt;element name="lista_piosenek" type="{}lista_piosenekType"/>
 *         &lt;element name="plajlista" type="{}plajlistaType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rootType", propOrder = {
    "metadane",
    "listaGatunkow",
    "listaWykonawcow",
    "listaPiosenek",
    "plajlista"
})
@XmlRootElement(name = "root")
public class RootType {

    @XmlElement(required = true)
    protected MetadaneType metadane;
    @XmlElement(name = "lista_gatunkow", required = true)
    protected ListaGatunkowType listaGatunkow;
    @XmlElement(name = "lista_wykonawcow", required = true)
    protected ListaWykonawcowType listaWykonawcow;
    @XmlElement(name = "lista_piosenek", required = true)
    protected ListaPiosenekType listaPiosenek;
    @XmlElement(required = true)
    protected List<PlajlistaType> plajlista;

    /**
     * Gets the value of the metadane property.
     * 
     * @return
     *     possible object is
     *     {@link MetadaneType }
     *     
     */
    public MetadaneType getMetadane() {
        return metadane;
    }

    /**
     * Sets the value of the metadane property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetadaneType }
     *     
     */
    public void setMetadane(MetadaneType value) {
        this.metadane = value;
    }

    /**
     * Gets the value of the listaGatunkow property.
     * 
     * @return
     *     possible object is
     *     {@link ListaGatunkowType }
     *     
     */
    public ListaGatunkowType getListaGatunkow() {
        return listaGatunkow;
    }

    /**
     * Sets the value of the listaGatunkow property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListaGatunkowType }
     *     
     */
    public void setListaGatunkow(ListaGatunkowType value) {
        this.listaGatunkow = value;
    }

    /**
     * Gets the value of the listaWykonawcow property.
     * 
     * @return
     *     possible object is
     *     {@link ListaWykonawcowType }
     *     
     */
    public ListaWykonawcowType getListaWykonawcow() {
        return listaWykonawcow;
    }

    /**
     * Sets the value of the listaWykonawcow property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListaWykonawcowType }
     *     
     */
    public void setListaWykonawcow(ListaWykonawcowType value) {
        this.listaWykonawcow = value;
    }

    /**
     * Gets the value of the listaPiosenek property.
     * 
     * @return
     *     possible object is
     *     {@link ListaPiosenekType }
     *     
     */
    public ListaPiosenekType getListaPiosenek() {
        return listaPiosenek;
    }

    /**
     * Sets the value of the listaPiosenek property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListaPiosenekType }
     *     
     */
    public void setListaPiosenek(ListaPiosenekType value) {
        this.listaPiosenek = value;
    }

    /**
     * Gets the value of the plajlista property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the plajlista property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlajlista().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlajlistaType }
     * 
     * 
     */
    public List<PlajlistaType> getPlajlista() {
        if (plajlista == null) {
            plajlista = new ArrayList<PlajlistaType>();
        }
        return this.plajlista;
    }

}
